### ISSUE TITLE
Project fails when loaded into VS

### ISSUE THREAD

**Issue by baronfel** [ionide/KeepAChangelog#8]
When 0.1.2 is loaded into VS, users get the following stack:

```
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018: The "Ionide.KeepAChangelog.Tasks.ParseChangeLogs" task failed unexpectedly.
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018: File name: 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018:    at Ionide.KeepAChangelog.Parser.parseChangeLog(FileInfo file)
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018:    at KeepAChangelog.Tasks.ParseChangelogs.Execute() in /_//src/Ionide.KeepAChangelog.Tasks/Library.fs:line 117
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>C:\Users\david\.nuget\packages\ionide.keepachangelog.tasks\0.1.2\build\Ionide.KeepAChangelog.Tasks.targets(14,9): error MSB4018: 
...
```

IMO this is because we need to support full-framework MSBuild targets. The `vs-support` branch tracks this need.

**Comment by baronfel** [comment]
Alternative idea - for net472 don't bundle fsharp.core at all and see if the ambient one from VS is picked up?

**Comment by Numpsy** [comment]
Can this one be closed now?
